name: Build VS2022

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: get-cmake
      uses: lukka/get-cmake@latest

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - uses: ilammy/msvc-dev-cmd@v1

    - name: build
      run: |
        wxEditor/external/build/vs2022/wxWidgets.bat
        external/build/vs2022/libgit2.bat
        build/vs2022/build.bat
