name: Build VS2019

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: get-cmake
      uses: lukka/get-cmake@latest

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: build
      run: build/vs2019/build.bat
